### ISSUE TITLE
Folders not ignored when added to .watchmanconfig in source folder

### ISSUE THREAD

**Issue by grisaitis** [wix/wml#40]
I'm developing a node module and want to exclude a `examples/` directory in the module folder. 

1. I added `"examples"` to the `"ignore_dirs"` list in the `module/.watchmanconfig` file. 
2. I added the wml task, with `wml add source/path/to/module /target/path/to/module`
3. Did `wml start`

And still, it copies over `examples/`. Which is a big folder. 

After 2., `wml add` still asked me if i wanted to ignore `.git` and `node_modules`. But these were already in `.watchmanconfig`.

Am I doing something wrong? Should I not edit `.watchmanconfig`?

Thanks for any help!

**Comment by rondinellimorais** [comment]
same problem here.

looks like `watchman` doesn't update your watch list after edit `.watchmanconfig`.

This steps work fine for me:

After `wml add`

1. edit `.watchmanconfig` and say what directories you want to ignore
2. clean watchman list running command `watchman  watch-del-all`, you can see the full list running `watchman watch-list`
3. `wml start`

repeat this steps every time you edit `.watchmanconfig`.

For the 2nd. This workaround work for me:
```
printf 'n\nn' | wml add
```

this will say **no** for the two questions

**Comment by numandev1** [comment]
@grisaitis this package is no longer maintain and has a lot of bugs. 

you can use this package
https://www.npmjs.com/package/mtsl

```
mtsl add -s ~/source-dir -d ~/User/destination-dir
mtsl start 0
```

this package is using chokidar instead of watchman

**Comment by grisaitis** [comment]
Thanks @nomi9995 

Closing out
