### ISSUE TITLE
wml start does nothing

### ISSUE THREAD

**Issue by Foskas** [wix/wml#47]
Hi,

I've followed the instructions to add wml working in my project and wml start does nothing. I'm currently using a new macbook pro with the M1 processor, but it was working fine with my previous intel macbook pro + big sur.

Any ideias how can I found the solution for the issue ?

**Comment by CesarBalzer** [comment]
Same problem

**Comment by scott-massey** [comment]
Same issue here, really frustrating

**Comment by somasekharkakarla** [comment]
same problem here
